### model
model_name_or_path: Qwen3-1.7B
trust_remote_code: true
add_tokens: <|AGENT|>, <|EDIT|>

### method
stage: sft
do_train: true
finetuning_type: full
# lora_rank: 8
# lora_target: all

### dataset
dataset: code_data
cutoff_len: 3000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /models/Qwen2.5_full
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
#report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 4
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
